package com.manta.app.core.model

/**
 * Windowed feature representation passed into detectors.
 */
data class FeatureWindow(
    val id: String,
    val appId: String,
    val windowStartMillis: Long,
    val windowEndMillis: Long,
    val flowCount: Int,
    val totalBytesOut: Long,
    val totalBytesIn: Long,
    val meanPacketSize: Double,
    val outboundRatio: Double,
    val burstiness: Double,
    val noveltyScore: Double,
    val connectionFrequencyDelta: Double,
    val bytesPerFlow: Double = 0.0,
    val destinationDiversity: Double = 0.0,
    val activityRatio: Double = 0.0,
    val byteRate: Double = 0.0,
    val packetRate: Double = 0.0,
    val meanDurationMillis: Double = 0.0,
    val durationJitter: Double = 0.0,
    val portDiversity: Double = 0.0,
    val protocolDiversity: Double = 0.0,
    val packetImbalance: Double = 0.0,
    val smallFlowRatio: Double = 0.0,
    val highPortRatio: Double = 0.0,
    val siteHint: String? = null,
    val periodicBeaconScore: Double = 0.0,
    val hourOfDay: Int = 0,
    val dayOfWeek: Int = 1,
    val isWeekend: Boolean = false,
    val dataQualityScore: Double = 1.0,
    val ttlGap: Double = 0.0,
    val ttlMetricsPresent: Double = 0.0,
    val synRateTotal: Double = 0.0,
    val rstRateTotal: Double = 0.0,
    val ackRateTotal: Double = 0.0,
    val finRateTotal: Double = 0.0,
    val pshRateTotal: Double = 0.0,
    val fragmentRateTotal: Double = 0.0,
    val tcpWindowMean: Double = 0.0,
    val ackDelayMean: Double = 0.0,
    val interPacketGapMean: Double = 0.0,
    val payloadMean: Double = 0.0,
    val loadMean: Double = 0.0,
    val transportMetricsPresent: Double = 0.0,
    val destinationConcentration: Double = 0.0,
    val destinationTransitionRate: Double = 0.0,
    val dnsFlowRatio: Double = 0.0,
    val webFlowRatio: Double = 0.0,
    val privateDestinationRatio: Double = 0.0,
    val multicastDestinationRatio: Double = 0.0,
    val flowCountDeviation: Double = 0.0,
    val byteRateDeviation: Double = 0.0,
    val destinationDiversityShift: Double = 0.0,
    val noveltyShift: Double = 0.0,
    val recentFlowCountMean: Double = 0.0,
    val recentByteRateMean: Double = 0.0,
    val recentNoveltyMean: Double = 0.0,
    val flowCountTrend: Double = 0.0,
    val byteRateTrend: Double = 0.0,
    val noveltyTrend: Double = 0.0,
    val destinationDiversityTrend: Double = 0.0,
    val consecutiveBurstWindows: Double = 0.0,
    val lowVolumePeriodicScore: Double = 0.0,
    val destinationRiskScore: Double = 0.0,
    val lookalikeScore: Double = 0.0,
    val suspiciousDestinationRatio: Double = 0.0,
    val knownIdentityRatio: Double = 0.0,
    val mitreTechniqueRatio: Double = 0.0,
    val threatTagRatio: Double = 0.0,
    val sampledByGuardrail: Boolean = false,
    val processingCostMillis: Double = 0.0
) {
    fun portableFeatureMap(): Map<String, Double> = mapOf(
        "flow_count" to flowCount.toDouble(),
        "total_bytes_out" to totalBytesOut.toDouble(),
        "bytes_out" to totalBytesOut.toDouble(),
        "total_bytes_in" to totalBytesIn.toDouble(),
        "bytes_in" to totalBytesIn.toDouble(),
        "mean_packet_size" to meanPacketSize,
        "outbound_ratio" to outboundRatio,
        "burstiness" to burstiness,
        "novelty_score" to noveltyScore,
        "novelty" to noveltyScore,
        "connection_frequency_delta" to connectionFrequencyDelta,
        "conn_freq_delta" to connectionFrequencyDelta,
        "bytes_per_flow" to bytesPerFlow,
        "destination_diversity" to destinationDiversity,
        "activity_ratio" to activityRatio,
        "periodic_beacon_score" to periodicBeaconScore,
        "byte_rate" to byteRate,
        "packet_rate" to packetRate,
        "mean_duration_ms" to meanDurationMillis,
        "duration_jitter" to durationJitter,
        "port_diversity" to portDiversity,
        "protocol_diversity" to protocolDiversity,
        "packet_imbalance" to packetImbalance,
        "small_flow_ratio" to smallFlowRatio,
        "high_port_ratio" to highPortRatio,
        "hour_of_day" to hourOfDay.toDouble(),
        "day_of_week" to dayOfWeek.toDouble(),
        "is_weekend" to if (isWeekend) 1.0 else 0.0,
        "data_quality_score" to dataQualityScore,
        "ttl_gap" to ttlGap,
        "ttl_metrics_present" to ttlMetricsPresent,
        "syn_rate_total" to synRateTotal,
        "rst_rate_total" to rstRateTotal,
        "ack_rate_total" to ackRateTotal,
        "fin_rate_total" to finRateTotal,
        "psh_rate_total" to pshRateTotal,
        "fragment_rate_total" to fragmentRateTotal,
        "tcp_window_mean" to tcpWindowMean,
        "ack_delay_mean" to ackDelayMean,
        "inter_packet_gap_mean" to interPacketGapMean,
        "payload_mean" to payloadMean,
        "load_mean" to loadMean,
        "transport_metrics_present" to transportMetricsPresent,
        "destination_concentration" to destinationConcentration,
        "destination_transition_rate" to destinationTransitionRate,
        "dns_flow_ratio" to dnsFlowRatio,
        "web_flow_ratio" to webFlowRatio,
        "private_destination_ratio" to privateDestinationRatio,
        "multicast_destination_ratio" to multicastDestinationRatio,
        "flow_count_deviation" to flowCountDeviation,
        "byte_rate_deviation" to byteRateDeviation,
        "destination_diversity_shift" to destinationDiversityShift,
        "novelty_shift" to noveltyShift,
        "recent_flow_count_mean" to recentFlowCountMean,
        "recent_byte_rate_mean" to recentByteRateMean,
        "recent_novelty_mean" to recentNoveltyMean,
        "flow_count_trend" to flowCountTrend,
        "byte_rate_trend" to byteRateTrend,
        "novelty_trend" to noveltyTrend,
        "destination_diversity_trend" to destinationDiversityTrend,
        "consecutive_burst_windows" to consecutiveBurstWindows,
        "low_volume_periodic_score" to lowVolumePeriodicScore,
        "destination_risk_score" to destinationRiskScore,
        "lookalike_score" to lookalikeScore,
        "suspicious_destination_ratio" to suspiciousDestinationRatio,
        "known_identity_ratio" to knownIdentityRatio,
        "mitre_technique_ratio" to mitreTechniqueRatio,
        "threat_tag_ratio" to threatTagRatio
    )

    companion object {
        val portableFeatureOrder = listOf(
            "flow_count",
            "total_bytes_out",
            "total_bytes_in",
            "mean_packet_size",
            "outbound_ratio",
            "burstiness",
            "novelty_score",
            "connection_frequency_delta",
            "bytes_per_flow",
            "destination_diversity",
            "activity_ratio",
            "periodic_beacon_score",
            "byte_rate",
            "packet_rate",
            "mean_duration_ms",
            "duration_jitter",
            "port_diversity",
            "protocol_diversity",
            "packet_imbalance",
            "small_flow_ratio",
            "high_port_ratio",
            "hour_of_day",
            "day_of_week",
            "is_weekend",
            "data_quality_score",
            "ttl_gap",
            "ttl_metrics_present",
            "syn_rate_total",
            "rst_rate_total",
            "ack_rate_total",
            "fin_rate_total",
            "psh_rate_total",
            "fragment_rate_total",
            "tcp_window_mean",
            "ack_delay_mean",
            "inter_packet_gap_mean",
            "payload_mean",
            "load_mean",
            "transport_metrics_present",
            "destination_concentration",
            "destination_transition_rate",
            "dns_flow_ratio",
            "web_flow_ratio",
            "private_destination_ratio",
            "multicast_destination_ratio",
            "flow_count_deviation",
            "byte_rate_deviation",
            "destination_diversity_shift",
            "novelty_shift",
            "recent_flow_count_mean",
            "recent_byte_rate_mean",
            "recent_novelty_mean",
            "flow_count_trend",
            "byte_rate_trend",
            "novelty_trend",
            "destination_diversity_trend",
            "consecutive_burst_windows",
            "low_volume_periodic_score",
            "destination_risk_score",
            "lookalike_score",
            "suspicious_destination_ratio",
            "known_identity_ratio",
            "mitre_technique_ratio",
            "threat_tag_ratio"
        )
    }
}
